# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example


name = "Starry"
description = "Clean Hugo. Calm Reading."
license = "MIT"
licenselink = "https://github.com/meethigher/hugo-theme-starry/LICENSE"
homepage = "https://github.com/meethigher/hugo-theme-starry"
demosite    = "https://meethigher.github.io"
min_version = "0.154.0"

tags = [ "blog", "personal", "light", "dark", "starry" ]

features = [
  "card-style layout",
  "responsive design",
  "light/dark mode",
  "table of contents",
  "image lazy loading",
  "image viewer",
  "mathjax lazy rendering",
  "indexdb fast search",
  "gitalk comments"
]

[author]
name = "meethigher"
homepage = "https://meethigher.top"
